name: 'CloudFrontDeploy'
description: 'CloudFrontDeploy'
inputs:
  source:
    description: 'Source path'
    required: true
  target:
    description: 'Target path'
    required: true
  cloudfront:
    description: 'CloudFront distribution'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
  args:
    - ${{ inputs.source }}
    - ${{ inputs.target }}
    - ${{ inputs.cloudfront }}
